### ISSUE TITLE
Feature: Date & Time in Chat bubble

### ISSUE THREAD

**Issue by ukanth** [dmitrizzle/chat-bubble#54]
It would be great to display date:time of the reply bubbles and even group them based on date.

**Comment by dmitrizzle** [comment]
Hey @ukanth how about adding a timestamp within bot's reply in a `<time></time>` tag as part of the content and styling it with CSS? Something like this:

```css
#chat time {
  display: block;
  font-size: .5em;
  color: #999;
}
```
```javascript
chatWindow.talk(
  {
    ice: {
      says: ["Hey!<time>" + new Date() + "</time>"]
    }
  }
)
```

-- you may also write a function that could add a date stamp automatically to every instance of your bot's conversation.
