### ISSUE TITLE
How i can add avatars?

### ISSUE THREAD

**Issue by Iilinkasa** [dmitrizzle/chat-bubble#90]
how is it possible to add 2 different avatars for a question and an answer?

**Comment by dmitrizzle** [comment]
Hey you can add avatars as HTML tags within your question/answer bubbles:

```javascript
var convo = {
  ice: {
    says: [
      "<span class="avatar liam"></span>Hi, I'm Liam.",
    ],
    reply: [
      {
        question:
          "<span class="avatar jose"></span>Hi, Liam, I'm José.",
        answer: "ice",
      },
    ]
  },
}
```

You can then turn those tags to look like whatever you want with CSS:
```css
span.avatar {
  display: inline-block;
  width: 1em;
  height: 1em;
  border-radius: 1em;
  background-color: red;
}
span.jose {
  background-color: blue;
}
```
